name: voici-dev
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - pandas
  - bqplot
  - ipyleaflet
  - ipywidgets
  - pip
  - pip:
    - pyproj
    - packaging
    - geopandas
    - shapely